# Change these first
owner: kevinlupera # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portafolio Kevin Lupera
    url: https://kevinlupera.github.io/
  - name: Google
    url: https://google.com
  - name: Amazon
    url: https://amazon.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    expectedStatusCodes:
      - 200
    
assignees: # Users to assign downtime issues (optional)
  - kevinlupera

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kevin Lupera Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitor status real-time
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
